# Scoring configuration for the job matching system

# Scoring component weights (must sum to 1.0)
weights:
  core_skills: 0.5
  experience: 0.2
  education: 0.15
  certifications: 0.15

# Education hierarchy (highest to lowest)
education_hierarchy:
  - "PhD"
  - "Master's"
  - "Bachelor's"
  - "Associate's"
  - "Diploma"
  - "High School"
  - "None"

# Threshold settings
thresholds:
  minimum_match_score: 40
  strong_match_threshold: 80
  weak_match_threshold: 30

# Debug mode (default)
debug_mode: false